### ISSUE TITLE
Why is OAuth required?

### ISSUE THREAD

**Issue by user-09876** [cedricdelpoux/gatsby-source-youtube#26]
Hello!

We're looking at using your gatsby plugin in our sites, because it's pretty cool to be able (that easily) to source youtube videos/playlists.

Generally when we're working with youtube API, we only use a youtube token, without the need of OAuth, to read video.

I wonder why with your plugin OAuth is required, and not "only a youtube API token"?

Cheers (and thanks for the plugin)!

**Comment by cedricdelpoux** [comment]
I use the official `googleapis` package that need an authentification.

https://github.com/cedricdelpoux/gatsby-source-youtube/blob/master/utils/source-nodes.js#L25-L29

But maybe there are other ways to request data that I'm not aware of.
If you find a simpler way and you are happy to help, PR are always welcome 🙂

**Comment by user-09876** [comment]
Alright, I understand the point of using the google sdk.
The thing is that currently it is complicated in my team's setup to get "an abstract google user" to register the whole process.
But generating a youtube read only API key, is not so complex.

Somehow it seems that it woud be:
- more secure (no oAuth with crazy access involved)
- simpler for the dev / devops experience, to only have one key
- easier for dev team to share these (important) secrets, because otherwise the development server does not run if these 3 env vars are not present

I will look at if there is a way to not require the 3 env vars, or if only a youtube api key is present, to use this one to make the calls.

PS: your plugin is pretty neat otherwise! And it is the only one that allows specifying playlist IDs

**Comment by cedricdelpoux** [comment]
> PS: your plugin is pretty neat otherwise! And it is the only one that allows specifying playlist IDs

Thanks ! I had a specific use case with playlist and I didn't found anything, that is why I implement it myself.

> I will look at if there is a way to not require the 3 env vars, or if only a youtube api key is present, to use this one to make the calls.

If you know some package using only an API key, please list them here

**Comment by user-09876** [comment]
> If you know some package using only an API key, please list them here

Here some I've found which only use Youtube data API key:
- https://www.npmjs.com/package/gatsby-source-youtube-playlist (but not github repo linked, would have to install the npm package to check its code)
- https://www.npmjs.com/package/gatsby-source-youtube-v2 
- https://www.npmjs.com/package/gatsby-source-youtube-v3

Cheers!

**Comment by cedricdelpoux** [comment]
Thanks. I think I need oauth to request some data that I can't request with an API key. I don't remember because I built this plugin 2 years ago. I can take a look but I don't have so much time right now. Babies twins are coming in few days for me. But PR are welcome if you want to help!
