### ISSUE TITLE
Allow user to set maximum number of videos

### ISSUE THREAD

**Issue by krismorf** [cedricdelpoux/gatsby-source-youtube#27]
At the moment there is a [default setting](https://github.com/cedricdelpoux/gatsby-source-youtube/blob/master/utils/constants.js#L3) that will only fetch 20 videos from each playlist.

**Comment by cedricdelpoux** [comment]
`PAGE_SIZE_VIDEOS` is not the maximun number of videos in the playlist.

I found that if I request more that 20 videos in 1 request, it could fail. 
So I request all videos in multiple request of 20 videos.

But maybe there is a bug. Did you find that the result only contain 20 videos?

**Comment by krismorf** [comment]
> Did you find that the result only contain 20 videos?

Correct, it only fetches 20 videos, but maybe I'm using it wrong, I only provide `playlistId` in my `gatsby-config.ts`

**Comment by cedricdelpoux** [comment]
@krismorf Thank you for reporting this. 
There was a bug indeed. I just fixed it in `2.5.1` version.
No need for an additional parameter. I will close your PR. Thank you for helping
